distro: trusty
sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
services:
  - mysql
before_script:
  - npm install grunt grunt-cli grunt-contrib-jshint grunt-contrib-csslint grunt-phplint --save-dev
  - mysql -u root -e "CREATE DATABASE rhymix CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON rhymix.* TO travis@localhost"
  - mysql -u root -e "UPDATE mysql.user SET Password = PASSWORD('travis') WHERE User = 'travis'; FLUSH PRIVILEGES"
  - phpenv config-rm xdebug.ini
  - php -S localhost:8000 &
  - wget http://codeception.com/releases/2.1.11/codecept.phar
script:
  - php codecept.phar build
  - php codecept.phar run -d --fail-fast --env travis
  - grunt lint
notifications:
  email: false
